### PR TITLE
4.24 fix (includes)

### PR DESCRIPTION
**Pull request by L05**
Fixed include files to update plugin for 4.24.

### CODE REVIEW

**Comment by monsieurgustav** [comment]
Thanks for the PR!
I'd like to merge only your latest commit "Update OscReceiverInputKey.cpp to remove sprintf warning."
The one about sprintf is another issue and I suspect sprintf_s() is not very portable anyway.

Can you update your PR with only this commit?
Or if you don't mind, I can cherry pick it myself. (but you would lose credit for it)

**Comment by L05** [comment]
Hi Guillaume, thanks for the message! Just to make sure I understand
correctly, I should remove the sprintf_s() call and return it to const auto
length = sprintf(buffer, "OSC%.500s", StringCast<ANSICHAR>(*address).Get());,
but keep everything else?

----------
Carlos Garcia
Software Engineer / Media Artist
//L05.is <http://l05.is/>

[image: L05-logo-small.png] <https://L05.is>

**Comment by monsieurgustav** [comment]
I don't know your git-fu level, but ideally you would have a branch from my "master" branch with a single commit on top of it containing the includes fix.

Alternatively, as you said, you could 'reverse' the sprintf commit, then I would squash them all.

**Comment by L05** [comment]
OK, I'll do that later today and ping you once it's done. Thanks!

----------
Carlos Garcia
Software Engineer / Media Artist
//L05.is <http://l05.is/>

[image: L05-logo-small.png] <https://L05.is>

**Comment by L05** [comment]
Hey Guillaume, I reverted the desired commit and submitted a new pull
request. I wasn't sure how to squash it all into one commit, but it sounds
like you know how. Let me know if anything else is needed. Thanks!

----------
Carlos Garcia
Software Engineer / Media Artist
//L05.is <http://l05.is/>

[image: L05-logo-small.png] <https://L05.is>

**Pull request merged**
